version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  commands:
    - pip install markdown
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - python -m markdown README.md > $READTHEDOCS_OUTPUT/html/index.html
