version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "latest"
    rust: "latest"
  commands:
    - pip install maturin
    - maturin build --features python --release
    - pip install --find-links=target/wheels/ automesh
    - mv docs/index.html $READTHEDOCS_OUTPUT/html/
