[book]
authors = ["Chad B. Hovey <chovey@sandia.gov>", "Michael R. Buche <mrbuche@sandia.gov>"]
description = "Automatic mesh generation."
language = "en"
src = "book/"
title = "automesh"

[build]
build-dir = "book/build/"
create-missing = false

[rust]
edition = "2018"

[preprocessor.katex]
after = ["links"]
