[package]
authors = ["Chad Brian Hovey <chovey@sandia.gov>", "Michael Robert Buche <mrbuche@sandia.gov>"]
categories = ["mathematics", "science"]
description = "automesh"
documentation = "https://github.com/autotwin/automesh"
edition = "2021"
homepage = "https://github.com/autotwin/automesh"
keywords = ["mesh"]
license = "MIT"
name = "automesh"
repository = "https://github.com/autotwin/automesh"
version = "0.1.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "=0.22", features = ["extension-module"]}

[profile.release]
codegen-units = 1
lto = false
