name: Python
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
env:
    CARGO_TERM_COLOR: always
on:
  pull_request:
    branches: main
  release:
    types: published
permissions: {}
jobs:
  Source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
      - name: netCDF
        run: sudo apt-get update && sudo apt-get install -y libnetcdf-dev
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Dependencies
        run: pip install build maturin twine
      - name: Source
        run: python -m build . --sdist
      - name: Check
        run: twine check dist/*
      - name: Dist
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
  Wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Toolchain
      uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
      with:
        toolchain: stable
    - name: netCDF
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux) sudo apt-get update && sudo apt-get install -y libnetcdf-dev ;;
          macOS) brew install netcdf ;;
          Windows)
            vcpkg install netcdf-c:x64-windows
            echo "C:/vcpkg/installed/x64-windows/bin" >> "$GITHUB_PATH"
            ;;
        esac
    - name: Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14
    - name: Dependencies
      run: pip install build maturin twine
    - name: Wheel
      run: maturin build --release
    - name: Check
      run: twine check target/wheels/*
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.os }}-dist
        path: target/wheels
  Twine:
    needs: [Source, Wheel]
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v8
    - name: Python
      uses: actions/setup-python@v6
      with:
        check-latest: true
        python-version: 3.14
    - name: Dependencies
      run: pip install twine
    - name: Wheels
      run: mv ./*-dist*/*.whl dist/
    - name: Upload
      if: github.event_name == 'release'
      run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
