name: Rust
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
env:
  CARGO_TERM_COLOR: always
on:
  pull_request:
    branches: main
  release:
    types: published
permissions: {}
jobs:
  Coverage:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: nightly
      - name: netCDF
        run: sudo apt-get update && sudo apt-get install -y libnetcdf-dev
      - name: Install
        run: cargo install cargo-llvm-cov
      - name: Coverage
        run: rustup run nightly cargo llvm-cov --profile release --fail-under-functions 59 --fail-under-lines 64 --fail-under-regions 55 || true
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: netCDF
        run: sudo apt-get update && sudo apt-get install -y libnetcdf-dev
      - name: Info
        run: sed -i "s/option_env!(\"GIT_COMMIT_HASH\").unwrap(),/\"$(git rev-parse --short HEAD)\".to_string(),/" src/main.rs
      - name: Package
        run: cargo package --allow-dirty
      - name: Login
        if: github.event_name == 'release'
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        if: github.event_name == 'release'
        run: cargo publish --allow-dirty
  Test:
    if: github.event_name != 'release'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [beta, stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.toolchain }}
      - name: netCDF
        shell: bash
        run: |
          case "${{ runner.os }}" in
            Linux) sudo apt-get update && sudo apt-get install -y libnetcdf-dev ;;
            macOS) brew install netcdf ;;
            Windows)
              vcpkg install netcdf-c:x64-windows
              echo "C:/vcpkg/installed/x64-windows/bin" >> "$GITHUB_PATH"
              ;;
          esac
      - name: Build
        run: cargo build --release
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Clippy tests
        run: cargo clippy --tests
      - name: Docs
        run: cargo rustdoc --release -- --html-in-header docs/katex.html
      - name: Format
        run: cargo fmt --all -- --check
      - name: Test
        run: cargo test --release
