name: Test
on:
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  Cargo:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --release -- -D warnings
